### ISSUE TITLE
目前编译不通过

### ISSUE THREAD

**Issue by bjdaijun** [somewhereMrli/albedo-boot#1]
目前的版本开发到什么程度了？可以在生产环境中试用吗？

**Comment by albedoboot** [comment]
当前项目框架就是从生产环境众提取出来的，你编译不能通过是报什么错？建议在maven - settings.xml文件中加入 
     <mirror>
      <id>alimaven</id>
      <name>aliyun maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
      <mirrorOf>central</mirrorOf>        
    </mirror>
以提高编译速度

**Comment by bjdaijun** [comment]
Eclipse的问题，已经解决了。
