### ISSUE TITLE
[err] albedo-boot-ui-vue>npm run dev

### ISSUE THREAD

**Issue by chenhui7373** [somewhereMrli/albedo-boot#31]
ERROR  Failed to compile with 1 errors                                                                         21:16:12

 error  in ./~/element-ui/packages/form/src/label-wrap.vue

Syntax Error: Unexpected token (23:14)
```


  21 |         }
  22 |       }
> 23 |       return (<div class="el-form-item__label-wrap" style={style}>
     |               ^
  24 |         { slots }
  25 |       </div>);
  26 |     } else {

```

 @ ./~/element-ui/packages/form/src/label-wrap.vue 4:2-100
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/element-ui/packages/form/src/form-item.vue
 @ ./~/element-ui/packages/form/src/form-item.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/modules/sys/user/info.vue
 @ ./src/views/modules/sys/user/info.vue
 @ ./src ^\.\/.*\.vue$
 @ ./src/util/util.js
 @ ./src/main.js
 @ ./src/entry-client.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./src/entry-client.js

**Comment by somowhere** [comment]
版本问题，用这个替换本地node_modules，即可
[element-ui.zip](https://github.com/somewhereMrli/albedo-boot/files/3388824/element-ui.zip)
