### ISSUE TITLE
非admin用户登录无法看到菜单

### ISSUE THREAD

**Issue by bjdaijun** [somewhereMrli/albedo-boot#4]
经测试，除了admin之外，其他用户登录无法看到左侧菜单。
![image](https://user-images.githubusercontent.com/1940592/27857461-5b0de2ac-61a4-11e7-8865-100c87e6833f.png)

**Comment by somewhereMrli** [comment]
已经修改l哈。更新试试

**Comment by bjdaijun** [comment]
fixed!
