### ISSUE TITLE
非admin用户登录，创建用户、组织或角色时，无法选择组织

### ISSUE THREAD

**Issue by bjdaijun** [somewhereMrli/albedo-boot#5]
![image](https://user-images.githubusercontent.com/1940592/27892311-83443018-6231-11e7-9ace-845b3a4364c5.png)

**Comment by somewhereMrli** [comment]
修复了哈，谢谢反馈

**Comment by bjdaijun** [comment]
👍

**Comment by bjdaijun** [comment]
更新代码后，还是不行。
1、
![image](https://user-images.githubusercontent.com/1940592/27907097-cae6fae4-6278-11e7-8940-a1eeae02eacb.png)

2、
![image](https://user-images.githubusercontent.com/1940592/27907112-dddefec6-6278-11e7-8f69-914a33d20f49.png)

**Comment by somewhereMrli** [comment]
已经修复了

**Comment by bjdaijun** [comment]
👍
