### ISSUE TITLE
代码生成功能报错

### ISSUE THREAD

**Issue by bjdaijun** [somewhereMrli/albedo-boot#8]
admin用户登录，点开业务表配置页面，报错：
![image](https://user-images.githubusercontent.com/1940592/27945833-61f2a32c-6321-11e7-972b-87a85fa29e66.png)
后台相关报错日志：
![image](https://user-images.githubusercontent.com/1940592/27945868-7dc9ef7e-6321-11e7-8a08-a99b33378384.png)

**Comment by somewhereMrli** [comment]
已经修复了
